on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run : node --version
      - run : npm -v
      - uses : actions/checkout@v3
      - run: npm install
      - run : npm run dev  
